### ISSUE TITLE
Benchmarking explanation? What does 100% mean?

### ISSUE THREAD

**Issue by makeitTim** [jails/php-router-benchmark#2]
The README has benchmark results with no explanation.

Presumably, 100% is the baseline? So, the smaller percent means faster? But the order and visuals make it look like the 100% is the best.

Either way, a quick sentence explaining what the results mean would be useful.

More context would also be useful... ie. benchmarked on standard shared php hosting we're talking differences in X ms.

**Comment by jails** [comment]
Yup 100% is the best. Smaller percent means that only X% of the job has been done when the fastest implementation finished the job.
